# Generated by Django 5.1.4 on 2025-05-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.IntegerField(choices=[(1, 'Electronics'), (2, 'Clothing'), (3, 'Home Appliances'), (4, 'Books'), (5, 'Sports Equipment')])),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('pimage', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
