# Generated by Django 5.1.4 on 2025-05-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'Mobiles'), (2, 'Clothing'), (3, 'Home Appliances'), (4, 'Electronics'), (5, 'Shoes')]),
        ),
    ]
