# Generated by Django 5.1.4 on 2025-05-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'Mobiles'), (2, 'Clothing'), (3, 'Home Appliances'), (4, 'Shoes')]),
        ),
    ]
